
# name: Detect Changed Services & Build

# on:
#   push:
#     paths:
#       - 'applications/**'
#       - '.github/workflows/github.yml'

# jobs:
#   detect-and-build:
#     runs-on: ubuntu-latest
#     env:
#       GOPRIVATE: github.com/PecozQ/*

#     steps:
#       - name: Checkout repository with full history
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Detect changed microservice
#         id: detect
#         run: |
#           BEFORE_SHA="${{ github.event.before }}"
#           if [ -z "$BEFORE_SHA" ] || ! git rev-parse "$BEFORE_SHA" >/dev/null 2>&1; then
#             BEFORE_SHA=$(git rev-parse HEAD^)
#           fi
#           echo "Using BEFORE_SHA: $BEFORE_SHA"

#           CHANGED_DIR=$(git diff --name-only $BEFORE_SHA ${{ github.sha }} | grep '^applications/' | cut -d/ -f2 | sort -u | head -n 1)
#           echo "Changed directory: $CHANGED_DIR"

#           if [ -n "$CHANGED_DIR" ]; then
#             echo "changed_dir=$CHANGED_DIR" >> $GITHUB_OUTPUT
#           else
#             echo "No changes detected under applications/. Skipping build."
#             exit 0
#           fi

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: '1.23.1'

#       - name: Configure Git for Private Module Access
#         run: |
#           git config --global url."https://${{ secrets.GH_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
#           echo "Configured Git to use PAT"

#       - name: Go mod tidy and vendor
#         if: steps.detect.outputs.changed_dir != ''
#         run: |
#           cd applications/${{ steps.detect.outputs.changed_dir }}
#           go mod tidy
#           go mod vendor

#       - name: Docker build
#         if: steps.detect.outputs.changed_dir != ''
#         run: |
#           IMAGE_NAME=nagagogulan/aimx-ext-${{ steps.detect.outputs.changed_dir }}
#           docker build -t $IMAGE_NAME:latest applications/${{ steps.detect.outputs.changed_dir }}

#       - name: Run docker-compose for the service
#         if: steps.detect.outputs.changed_dir != ''
#         run: |
#           SERVICE_NAME=ext-${{ steps.detect.outputs.changed_dir }}
#           docker-compose -f docker-compose-ext-server.yml up -d $SERVICE_NAME


name: Go CI for Private Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOPRIVATE: github.com/PecozQ/*

jobs:
  build:
    name: Build Go Project with Private Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1' # Update to your Go version

      - name: Setup SSH for GitHub (Private Modules)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          echo "✅ SSH configured for GitHub access"

      - name: Download Go Modules
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Run Tests
        run: go test ./...
