name: Detect Changed Services & Build

on:
  push:
    paths:
      - 'applications/**'
      - '.github/workflows/github.yml'

jobs:
  detect-and-build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/PecozQ/*

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed microservice
        id: detect
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          if [ -z "$BEFORE_SHA" ] || ! git rev-parse "$BEFORE_SHA" >/dev/null 2>&1; then
            BEFORE_SHA=$(git rev-parse HEAD^)
          fi
          echo "Using BEFORE_SHA: $BEFORE_SHA"

          CHANGED_DIR=$(git diff --name-only $BEFORE_SHA ${{ github.sha }} | grep '^applications/' | cut -d/ -f2 | sort -u | head -n 1)
          echo "Changed directory: $CHANGED_DIR"

          if [ -n "$CHANGED_DIR" ]; then
            echo "changed_dir=$CHANGED_DIR" >> $GITHUB_OUTPUT
          else
            echo "No changes detected under applications/. Skipping build."
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Set Go environment variables
        run: |
          go env -w GO111MODULE=on
          go env -w GOPRIVATE=github.com/PecozQ/*

      - name: Configure Git for private module access via HTTPS with token
        run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Clone aimx-library (private module)
        run: git clone https://github.com/PecozQ/aimx-library.git

      - name: Go mod tidy and vendor
        if: steps.detect.outputs.changed_dir != ''
        run: |
          cd applications/${{ steps.detect.outputs.changed_dir }}
          go mod tidy
          go mod vendor

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Docker build
        if: steps.detect.outputs.changed_dir != ''
        run: |
          IMAGE_NAME=nagagogulan/aimx-ext-${{ steps.detect.outputs.changed_dir }}
          docker build -t $IMAGE_NAME:latest applications/${{ steps.detect.outputs.changed_dir }}

      - name: Create external volume 'shared-data'
        run: docker volume create shared-data
    

      - name: Run docker-compose for the service
        if: steps.detect.outputs.changed_dir != ''
        run: |
          SERVICE_NAME=ext-${{ steps.detect.outputs.changed_dir }}
          docker-compose -f docker-compose-ext-server.yml up -d $SERVICE_NAME
